version: "3.7"
services:
  streamlit:
    build: ./
    container_name: tools
    ports:
      - "8888:8888"
    working_dir: "/workspaces/tools"
    volumes:
      - /Volumes/myDriver/Github/tools:/workspaces/tools
    command: "streamlit run auth.py --server.port 8888"